import { z } from 'zod';

/**
 * Content schemas.
 *
 * Every piece of project content is parsed through these at module load,
 * which means a malformed content file fails `next build` rather than
 * rendering a silently empty section in production.
 *
 * These schemas are also the contract a future headless CMS must satisfy.
 * Swapping Sanity/Contentful in later means writing a mapper that returns
 * this shape — no component or route changes.
 */

/** An image in `public/`. Dimensions are required so next/image can reserve
 *  space and avoid layout shift. */
export const imageSchema = z.object({
  /** Root-relative path, e.g. `/projects/sora-matcha/hero-tin-bowl.jpg` */
  src: z.string().startsWith('/'),
  /** Describes the image content. Empty string marks it as decorative. */
  alt: z.string(),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  /** Tiny base64 JPEG shown while the real image loads. Generated by
   *  `scripts/generate-blur.mjs`; never hand-written. */
  blurDataURL: z.string().startsWith('data:image/').optional(),
});

/* ---- case study blocks -------------------------------------------------
   The block list is what makes each case study individually art-directed
   without any bespoke components. Adding a layout = adding one variant
   here plus one renderer branch.
   --------------------------------------------------------------------- */

/** Surface a full-bleed band sits on. `ink` is the site default; the others
 *  are a project's own identity colours. Adding a tone here is the only way a
 *  case study is allowed to introduce colour. */
const toneSchema = z.enum(['ink', 'paper', 'green', 'maroon']).default('ink');

const bleedBlock = z.object({
  type: z.literal('bleed'),
  image: imageSchema,
  caption: z.string().optional(),
  tone: toneSchema,
  /** Photographs fill the band; artwork on paper sits inside it uncropped. */
  fit: z.enum(['cover', 'contain']).default('cover'),
});

const headingBlock = z.object({
  type: z.literal('heading'),
  /** Letter shown in the section rule, e.g. "A". */
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  note: z.string().optional(),
});

const noteBlock = z.object({
  type: z.literal('note'),
  text: z.string().min(1),
});

/** A normal-width paragraph — for passages too long to read as a pull-quote
 *  (`note`'s narrow, large-type treatment) but still just prose, no image.
 *  Reuses the site's existing global `.prose` type class. `variant:
 *  'reflection'` is for the closing statement only — visually distinct
 *  from a standard prose paragraph so it reads as the final word, not
 *  another paragraph in the sequence. */
const proseBlock = z.object({
  type: z.literal('prose'),
  text: z.string().min(1),
  variant: z.enum(['default', 'reflection']).default('default'),
});

const fullBlock = z.object({
  type: z.literal('full'),
  image: imageSchema,
  caption: z.string().optional(),
});

const pairBlock = z.object({
  type: z.literal('pair'),
  images: z.tuple([imageSchema, imageSchema]),
  captions: z.tuple([z.string(), z.string()]).optional(),
});

const triptychBlock = z.object({
  type: z.literal('triptych'),
  images: z.tuple([imageSchema, imageSchema, imageSchema]),
  captions: z.tuple([z.string(), z.string(), z.string()]).optional(),
});

/** Full-bleed dark section with a horizontally scrolling row. */
const galleryBlock = z.object({
  type: z.literal('gallery'),
  tone: toneSchema,
  title: z.string().min(1),
  note: z.string().optional(),
  text: z.string().optional(),
  images: z.array(imageSchema).min(2),
});

/** A sequential journey/service-blueprint: stage, emotional temperature,
 *  and the design response at that stage. Renders as a stepped list —
 *  horizontal on wide viewports, stacked on narrow ones. Use sparingly:
 *  one per case study, only when the project's UX/service-design thinking
 *  needs a structure `note`/`heading` blocks can't carry. */
const timelineBlock = z.object({
  type: z.literal('timeline'),
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  note: z.string().optional(),
  steps: z
    .array(
      z.object({
        stage: z.string().min(1),
        feeling: z.string().min(1),
        text: z.string().min(1),
        /** Emotional temperature at this stage, 0–100. Plots the line in the
         *  native SVG diagram above the steps — optional so a timeline can
         *  be added without immediately having to quantify every stage. */
        tone: z.number().min(0).max(100).optional(),
      }),
    )
    .min(3),
});

/** A comparison panel: a short list on one side, a finding on the other.
 *  Built for a research beat ("what I looked at" / "what I found"), but
 *  generic enough for any two-position argument. */
const compareBlock = z.object({
  type: z.literal('compare'),
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  left: z.object({ title: z.string().min(1), items: z.array(z.string().min(1)).min(1) }),
  right: z.object({ title: z.string().min(1), text: z.string().min(1) }),
});

/** A full-screen, minimal editorial statement — the emotional beat of a
 *  case study. Use at most twice: once to open (the insight), once to
 *  close (the reflection). Anything more and it stops feeling rare. */
const interludeBlock = z.object({
  type: z.literal('interlude'),
  lines: z.array(z.string().min(1)).min(1),
});

/** Wraps the site's existing ColumnGrid (home, capabilities) for a 3-up
 *  set of titled principles inside a case study. */
const columnsBlock = z.object({
  type: z.literal('columns'),
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  note: z.string().optional(),
  items: z
    .array(z.object({ marker: z.string().min(1), title: z.string().min(1), body: z.string().min(1) }))
    .min(2)
    .max(4),
});

/** The visual-language reference board — a source image, a colour palette,
 *  and a couple of motifs — revealed progressively as the section scrolls
 *  into view rather than shown flat all at once. One per case study. */
const visualLanguageBlock = z.object({
  type: z.literal('visualLanguage'),
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  note: z.string().optional(),
  text: z.string().min(1),
  reference: imageSchema,
  palette: z.array(z.object({ hex: z.string().min(1), label: z.string().min(1) })).min(1),
  motifs: z.array(z.object({ src: z.string().min(1), label: z.string().min(1) })).min(1),
});

const annotateBlock = z.object({
  type: z.literal('annotate'),
  marker: z.string().min(1).max(3),
  title: z.string().min(1),
  note: z.string().optional(),
  image: imageSchema,
  /** Each note reveals as it is read, and draws a hairline to its detail.
   *  `x`/`y` are percentages of the image box. */
  notes: z
    .array(
      z.object({
        label: z.string().min(1),
        text: z.string().min(1),
        x: z.number().min(0).max(100),
        y: z.number().min(0).max(100),
      }),
    )
    .min(2)
    .max(6),
});

/** A composed set of images read as one artefact rather than as a sequence.
 *  Use it wherever three or more images say a single thing — four reference
 *  sheets, a shoot from one session — because stacking those as separate
 *  full-width blocks makes each one a statement and turns the page into a
 *  contact sheet.
 *
 *  Two layouts, and the difference is whether cropping is allowed:
 *  - `even`    tiles at natural aspect, nothing cropped. For artwork, sketch
 *              pages and reference sheets, where the edge of the sheet is
 *              part of what is being shown.
 *  - `feature` gives the first image a double cell and crops the rest square.
 *              For photography, where a crop is a composition and five frames
 *              want to read as one spread. Five images tile it exactly. */
const mosaicBlock = z.object({
  type: z.literal('mosaic'),
  marker: z.string().min(1).max(3).optional(),
  title: z.string().min(1).optional(),
  note: z.string().optional(),
  text: z.string().optional(),
  layout: z.enum(['even', 'feature']).default('even'),
  images: z.array(imageSchema).min(3).max(6),
  captions: z.array(z.string()).optional(),
});

/** A single story card given its own viewport and its own ground colour.
 *  Bilingual by design — the Hindi is not a translation of the English, it is
 *  half of the artefact. */
const storyBlock = z.object({
  type: z.literal('story'),
  tone: z.enum(['green', 'maroon', 'brown']),
  /** The line pulled out before the card itself is shown. */
  pull: z.string().min(1),
  region: z.string().min(1),
  dish: z.string().min(1),
  image: imageSchema,
  english: z.string().min(1),
  hindi: z.string().min(1),
});

export const blockSchema = z.discriminatedUnion('type', [
  annotateBlock,
  storyBlock,
  bleedBlock,
  headingBlock,
  noteBlock,
  proseBlock,
  fullBlock,
  pairBlock,
  triptychBlock,
  mosaicBlock,
  galleryBlock,
  timelineBlock,
  compareBlock,
  interludeBlock,
  columnsBlock,
  visualLanguageBlock,
]);

/* ---- project ---------------------------------------------------------- */

export const projectSchema = z.object({
  /** URL segment: /projects/<slug> — lowercase, hyphenated. */
  slug: z
    .string()
    .min(1)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'slug must be lowercase and hyphenated'),
  /** Two-digit index shown in the UI, e.g. "01". */
  index: z.string().regex(/^\d{2}$/),
  title: z.string().min(1),
  /** Short qualifier under the title, e.g. "Ceremonial matcha". */
  kicker: z.string().min(1),
  discipline: z.string().min(1),
  year: z.string().regex(/^\d{4}$/),
  /** One-sentence summary. Doubles as the meta description fallback. */
  summary: z.string().min(1),
  /** Card/preview image. Also the Open Graph image fallback. */
  thumbnail: imageSchema,
  /** Optional opening statement, rendered before the facts grid. Omit it and
   *  a project falls back to the plain text-led opening (SORA's treatment).
   *
   *  Two forms, because two projects need opposite things. `lines` is a
   *  typographic opening — used where a photograph read as "an object"
   *  rather than an experience. `image` is a single contained drawing on
   *  the site's own paper — used where the drawing *is* the concept and
   *  any words in front of it would be an explanation nobody asked for. */
  hero: z
    .object({
      lines: z.array(z.string().min(1)).min(1).optional(),
      image: imageSchema.optional(),
    })
    .refine((h) => Boolean(h.lines) !== Boolean(h.image), {
      message: 'hero takes either lines or an image, not both and not neither',
    })
    .optional(),
  meta: z.object({
    client: z.string().min(1),
    role: z.string().min(1),
    timeframe: z.string().min(1),
    scope: z.string().min(1),
    tools: z.string().min(1),
    /** Short discipline tag(s), e.g. "Service Design · Brand Experience" —
     *  shown as "Project Type" in the compact overview. Optional so
     *  existing projects (SORA) don't need to add it. */
    type: z.string().min(1).optional(),
  }),
  overview: z.string().min(1),
  approach: z.array(z.string().min(1)).min(1),
  outcome: z.string().min(1),
  /** Optional. A project with no meaningful figures should not invent three
   *  to fill a row — and a case study that ends on a reflection should not
   *  then follow it with an inventory. */
  metrics: z
    .array(z.object({ label: z.string().min(1), value: z.string().min(1) }))
    .min(1)
    .optional(),
  blocks: z.array(blockSchema),
  /** The process, held on its own page at /projects/<slug>/research.
   *
   *  The case study answers what the problem was, what was decided and what
   *  came out of it. Everything that evidences those decisions — studies,
   *  iterations, dielines, the things that failed — belongs here instead, so
   *  the case study stays readable and the depth is still one click away for
   *  anyone who wants it. Same block vocabulary; it is a second ordered list,
   *  not a second format. */
  research: z
    .object({
      /** Sentence under the research page's heading. */
      intro: z.string().min(1),
      blocks: z.array(blockSchema).min(1),
    })
    .optional(),
  /** Optional per-project SEO overrides; sensible defaults are derived. */
  seo: z
    .object({
      title: z.string().optional(),
      description: z.string().optional(),
    })
    .optional(),
  /** Unpublished projects are excluded from listings, sitemap and routes. */
  published: z.boolean().default(true),
});

/* ---- journal ---------------------------------------------------------- */

export const journalPostSchema = z.object({
  slug: z
    .string()
    .min(1)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'slug must be lowercase and hyphenated'),
  title: z.string().min(1),
  /** ISO date, e.g. "2026-03-14". */
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  summary: z.string().min(1),
  body: z.array(z.string().min(1)),
  published: z.boolean().default(true),
});
